[package]
name = "indicium"
version = "0.1.3"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2018"
categories = [ "database-implementations" ]
description = "A simple search engine for collections and key-value stores."
documentation = "https://docs.rs/indicium"
keywords = [ "search", "autocomplete", "typeahead", "struct", "collection" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/indicium"

[dependencies]
regex = "1"