[package]
name = "indicium"
version = "0.2.0"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2018"
categories = [ "database-implementations" ]
description = "Simple search engine for collections and key-value stores."
documentation = "https://docs.rs/indicium"
keywords = [ "search", "autocomplete", "struct", "vec", "hashmap" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/indicium"

[features]
default = ["rayon", "simple", "select2"]
simple = []
select2 = ["serde"]

[dependencies]
derive_builder = "0.10"
rayon = { version = "1.5", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }