[package]
name = "indicium"
version = "0.3.4"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2021"
categories = [ "database-implementations" ]
description = "Simple in-memory search for collections and key-value stores."
documentation = "https://docs.rs/indicium"
keywords = [ "search", "autocomplete", "struct", "vec", "hashmap" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/indicium"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = [ "simple" ]
simple = []
select2 = [ "simple", "serde" ]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
tracing = "0.1"